###############################
# Servicio: PostgreSQL Airflow
###############################
services:

  postgres_airflow:
    image: postgres:15
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    networks:
      - red_bigdata

###############################
# Servicio: Apache Airflow
###############################
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: airflow:2.9.1-spark-client
    container_name: airflow_bigdata
    restart: unless-stopped
    depends_on:
      - postgres_airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW_UID: 50000
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./.env:/opt/airflow/.env:ro
      - ./:/opt/airflow/project
    command: >
      bash -c "
        airflow db upgrade &&
        airflow users create
          --username admin --password admin
          --firstname Admin --lastname User
          --role Admin --email admin@example.com &&
        airflow scheduler & exec airflow webserver
      "
    networks:
      - red_bigdata

volumes:
  airflow_pgdata:

networks:
  red_bigdata:
    external: true
